/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { notoSansJP, roboto } from "@/libs/fonts";
import "./globals.css";
import { GlobalNavigation } from "@/components/layout/GlobalNavigation/GlobalNavigation";
import { ReactQueryProvider } from "./providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${roboto.variable} ${notoSansJP.variable} h-full`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=account_circle,account_circle_off,calendar_clock,calendar_month,edit_note,help,home,image_arrow_up,landscape_2,login,logout,palette,robot,robot_2,schedule,search,smart_toy&display=block"
        />
      </head>
      <body>
        <ReactQueryProvider>
        <GlobalNavigation />
        {children}
        <Toaster position="top-center" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
